spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupang
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}
    username: elastic
    password: ${ELASTICSEARCH_PASSWORD}
logging:
  level:
    org.elasticsearch.client: TRACE